version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    networks:
      - cra-network
    depends_on:
      - backend

  backend:
    image: craweb/cra-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - cra-network
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=cra_db
      - POSTGRES_USER=cra_user
      - POSTGRES_PASSWORD=cra_password
    ports:
      - "5432:5432"
    networks:
      - cra-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  cra-network:
    driver: bridge